# Generated by Django 5.0.4 on 2024-04-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('yes', models.CharField(max_length=50, verbose_name='yes')),
                ('no', models.CharField(max_length=50, verbose_name='no')),
            ],
        ),
    ]
